### ISSUE TITLE
SQLALCHEMY is Updated and you need to fix it

### ISSUE THREAD

**Issue by zohaib258** [UmanSheikh/Todo-app#1]
Python library SQLALCHEMY has updated and hence some functions are updated so you need to change your code because it is not running.

**Comment by UmanSheikh** [comment]
Yeah I check it but I am not interested in my starting projects so, I will just close it and I am looking forward in some other projects. Hopefully I will make some of them open source and It will be a pleasure for me if you collaborate with me on upcoming projects. See you soon.
